### ISSUE TITLE
DNS Resolution issue on google and cloudflare for deployed service

### ISSUE THREAD

**Issue by Joe-Dowd** [lpinca/binb#35] opened 2020-01-16 04:36 UTC
I've having issues accessing your deployed binb.co service.
https://176.56.237.4/ works fine, but it looks like the major dns providers are not resolving the domain properly.

I'm fairly certain this is a wider issue than me personally due to the reduced number of current users.

```
 ~ $ nslookup binb.co 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find binb.co: SERVFAIL

 ~ $ nslookup binb.co 1.1.1.1
Server:		1.1.1.1
Address:	1.1.1.1#53

** server can't find binb.co: SERVFAIL

~ $ nslookup binb.co 192.168.0.1
Server:		192.168.0.1
Address:	192.168.0.1#53

Non-authoritative answer:
Name:	binb.co
Address: 176.56.237.4
```
192.168.0.1 is my ISP provided dns server, I have no information about the upstream servers.

**Comment by lpinca** [comment] 2020-01-17 17:00
I can't reproduce. It works fine in all places (in Italy) where I have tested it.

**Comment by Joe-Dowd** [comment] 2020-01-17 17:12
Yeah I re-tested the next day and it seems to be working fine again -
apologies, must have been me.

**Comment by lpinca** [comment] 2020-01-17 17:17
No problem. Closing then.

**Closed by lpinca** 2020-01-17 17:17 UTC
